# -*- coding: utf-8 -*-
"""RAG-based AI solution_Merck_Manuals_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P54uDGNvlS-qoSjtId20Ls78bf4PLs46

### Business Context

The healthcare industry is rapidly evolving, with professionals facing increasing challenges in managing vast volumes of medical data while delivering accurate and timely diagnoses. The need for quick access to comprehensive, reliable, and up-to-date medical knowledge is critical for improving patient outcomes and ensuring informed decision-making in a fast-paced environment.

Healthcare professionals often encounter information overload, struggling to sift through extensive research and data to create accurate diagnoses and treatment plans. This challenge is amplified by the need for efficiency, particularly in emergencies, where time-sensitive decisions are vital. Furthermore, access to trusted, current medical information from renowned manuals and research papers is essential for maintaining high standards of care.

To address these challenges, healthcare centers can focus on integrating systems that streamline access to medical knowledge, provide tools to support quick decision-making, and enhance efficiency. Leveraging centralized knowledge platforms and ensuring healthcare providers have continuous access to reliable resources can significantly improve patient care and operational effectiveness.

**Common Questions to Answer**

**1. Diagnostic Assistance**: "What are the common symptoms and treatments for pulmonary embolism?"

**2. Drug Information**: "Can you provide the trade names of medications used for treating hypertension?"

**3. Treatment Plans**: "What are the first-line options and alternatives for managing rheumatoid arthritis?"

**4. Specialty Knowledge**: "What are the diagnostic steps for suspected endocrine disorders?"

**5. Critical Care Protocols**: "What is the protocol for managing sepsis in a critical care unit?"

### Objective

As an AI specialist, my  task is to develop a RAG-based AI solution using renowned medical manuals to address healthcare challenges. The objective is to **understand** issues like information overload, **apply** AI techniques to streamline decision-making, **analyze** its impact on diagnostics and patient outcomes, **evaluate** its potential to standardize care practices, and **create** a functional prototype demonstrating its feasibility and effectiveness.

### Data Description

The **Merck Manuals** are medical references published by the American pharmaceutical company Merck & Co., that cover a wide range of medical topics, including disorders, tests, diagnoses, and drugs. The manuals have been published since 1899, when Merck & Co. was still a subsidiary of the German company Merck.

The manual is provided as a PDF with over 4,000 pages divided into 23 sections.

## Installing and Importing Necessary Libraries and Dependencies
"""

#Vishwa imports
import sys
import os
import time
import numpy as np
# Importing the library for data manipulation
import pandas as pd
# to visualise data
import matplotlib.pyplot as plt
import seaborn as sns

#from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

!pip install langchain langchain-community
!pip install -q transformers accelerate bitsandbytes

# Commented out IPython magic to ensure Python compatibility.
#This section needs to run each time Google Colab session gets reset.
# Upgrade build tooling
# %pip install -q --upgrade pip setuptools wheel

# Pin NumPy to what your stack expects
# %pip uninstall -y numpy
# %pip install -q numpy==1.25.2

# Restore your project pins
# %pip install -q huggingface_hub==0.25.2 pandas==1.5.3 tiktoken==0.6.0 \
    pymupdf==1.25.1 langchain==0.1.1 langchain-community==0.0.13 \
    chromadb==0.4.22 sentence-transformers==2.3.1

#The other version you might want to try, if you run into issues is: llama-cpp-python==0.3.2
# Installation for GPU llama-cpp-python
# uncomment and run the following code in case GPU is being used
!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python==0.1.85 --force-reinstall --no-cache-dir -q

# Installation for CPU llama-cpp-python
# uncomment and run the following code in case GPU is not being used
# !CMAKE_ARGS="-DLLAMA_CUBLAS=off" FORCE_CMAKE=1 pip install llama-cpp-python==0.1.85 --force-reinstall --no-cache-dir -q

#Libraries for processing dataframes,text
!pip install tiktoken
import json,os
import tiktoken
import pandas as pd
#!pip install llama-cpp-python
# System packages for pdf → image and OCR
!apt-get -y install poppler-utils tesseract-ocr

# Python libraries
!pip install --upgrade pypdf pdfplumber pdf2image pytesseract tqdm
!pip install faiss-cpu sentence-transformers


#Libraries for Loading Data, Chunking, Embedding, and Vector Databases
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_community.embeddings.sentence_transformer import SentenceTransformerEmbeddings
from langchain_community.vectorstores import Chroma


!pip install pypdf
!pip install pytesseract
!pip install pdf2image
!pip install pdfplumber
import pytesseract
from pdf2image import convert_from_path
import pdfplumber
from pypdf import PdfReader
from tqdm.auto import tqdm
import re

# Commented out IPython magic to ensure Python compatibility.
#Imports - II
import faiss
import numpy as np
# 🔑 Explicitly pin compatible transformers + accelerate
# %pip install -q transformers==4.36.2 accelerate==0.26.1
from sentence_transformers import SentenceTransformer

"""## Loading the dataset"""

#Vishwa: Load the necessary files
# loading the dataset
import os, gc, re, json, shutil
from pathlib import Path
from google.colab import drive
drive.mount('/content/drive')
Base_Dir = Path("/content/drive/MyDrive")
os.chdir(Base_Dir)

"""##Configuration paths, definitions of the Merck Manual PDF"""

OUTPUT_DIR = "/content/merck_splits"
pdf_fullpath = "/content/drive/MyDrive/medical_diagnosis_manual.pdf";

# ==== OUTPUT WORKSPACE ====
#The Base_Dir is already loaded earlier
#Base_Dir = Path("/content/drive/MyDrive")
DIR_PAGES   = Base_Dir / "pages_text"   # per-page text (OCR/normal)
DIR_CHUNKS  = Base_Dir / "chunks"       # individual chunk .txt files
DIR_META    = Base_Dir / "meta"         # mapping/jsonl
DIR_INDEX   = Base_Dir / "index"        # FAISS index + model name
meta_jsonl_path = Base_Dir / "chunks_meta.jsonl"

for d in [Base_Dir, DIR_PAGES, DIR_CHUNKS, DIR_META, DIR_INDEX]:
    d.mkdir(parents=True, exist_ok=True)


# ==== CHUNK & EMBEDDING ====
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 150
#Remember - This model is used only for embedding the document vectors . This is not for chat responses.
EMBED_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
BATCH_EMBED = 64        # embed this many chunks at a time (tune down if RAM is tight. I think this should work fine with Google Colab.)
BATCH_PDF_PAGES = 80    # process this many PDF pages before forcing a GC (#Vishwa: Lets see if this default configuration works. )

TOP_K = 8  # retrieval default

def extract_outline(outlines, result=None):
    if result is None:
        result = []
    for item in outlines:
        if isinstance(item, list):   # nested (chapters under sections)
            extract_outline(item, result)
        else:
            try:
                title = item.title
                page_num = reader.get_destination_page_number(item) + 1  # convert to 1-based
                result.append((title, page_num))
            except Exception as e:
                print(f"Skipping item due to error: {e}")
    return result

def flatten_outline(items, acc=None):
    if acc is None: acc = []
    for it in items:
        if isinstance(it, list):
            flatten_outline(it, acc)
        else:
            try:
                title = it.title
                page1 = reader.get_destination_page_number(it) + 1  # 1-based
                acc.append((title, page1))
            except Exception:
                pass
    return acc

"""##Outline Section Page Ranges"""

#Vishwa..Read the file stock_news that is provided
#data_original = pd.read_csv("medical_diagnosis_manual.pdf")
#Vishwa: TBD: Need to see if there are other mechanisms to efficiently read a pdf file embedded with images
reader = PdfReader(pdf_fullpath)
# total number of pages
num_pages = len(reader.pages)
print("Total pages in PDF:", num_pages)
try:
    raw_outline = reader.outline
except Exception:
    raw_outline = []

outline = flatten_outline(raw_outline)
outline = sorted(outline, key=lambda x: x[1])

# Build section ranges (title -> [start_page, end_page])
section_ranges = {}
if outline:
    for i, (title, start) in enumerate(outline):
        end = (outline[i+1][1]-1) if i+1 < len(outline) else num_pages
        section_ranges[title] = (start, end)
else:
    section_ranges = {"FULL_DOCUMENT": (1, num_pages)}

print(f"Pages: {num_pages}")
print(f"Sections detected: {len(section_ranges)}")
list(section_ranges.items())[:5]

"""The above output confirms that the pdf does have the Table of Content. So we could write code to systematically save these 23 different sections/chapters

##Page extraction (structured text first, OCR fallback), with disk caching

  The per-page cache means if Colab disconnects, you won’t redo OCR; it will just load the text files.
"""

def page_text_cached(page_num_zero_based):
    """Return text for a page (0-based), using cache if available.
       Tries pdfplumber text first; if empty → OCR the page image."""
    p1 = page_num_zero_based + 1
    cache_file = DIR_PAGES / f"page_{p1:06d}.txt"
    if cache_file.exists():
        return cache_file.read_text(encoding="utf-8", errors="ignore")

    # Not cached: extract
    text = ""
    with pdfplumber.open(str(pdf_fullpath)) as pdf:
        pg = pdf.pages[page_num_zero_based]
        text = pg.extract_text() or ""

    if not text.strip():
        # OCR fallback: render only this page
        img = convert_from_path(str(pdf_fullpath), first_page=p1, last_page=p1)[0]
        text = pytesseract.image_to_string(img)

    cache_file.write_text(text or "", encoding="utf-8")
    return text

print("Warming up first 3 pages ...")
_ = [page_text_cached(i) for i in range(min(10, num_pages))]
print("OK.")

"""## Writing the Indexes onto the disk. Includes the One time ingestion code that writes onto Disk
###Streaming chunking + embedding into FAISS (no giant lists in RAM)

  We do not keep all chunks in memory. Write each chunk to DIR_CHUNKS as a file and record its metadata in a JSONL mapping. We embed in batches and add to FAISS as we go.

**Approach Note (Knowledge Base section):**

FAISS workflow for this solutioning, looks like this:

 1. Chunk text (split Merck Manual into ~1000-character pieces).

 2. Embed each chunk into a vector (e.g., 384-d floats from all-MiniLM-L6-v2).

 3. Add embeddings to FAISS index → stored on disk as faiss.index.

Later, when you have a query:

 - Embed the query into a vector.

 - Ask FAISS: “Give me the top k nearest neighbors by similarity.”

 - FAISS returns the row IDs of the closest chunks.

 - Use those chunks as context for the LLM in RAG.
"""

!pip uninstall -y transformers accelerate
!pip install -q transformers==4.36.2 accelerate==0.26.1
#Preparation code to fetch the indexed data from the disk
# Prepare FAISS (cosine similarity via inner-product with normalized embeddings)
emb_model = SentenceTransformer(EMBED_MODEL_NAME)
vec_dim = emb_model.get_sentence_embedding_dimension()

# Vishwa : We can chose various indexing mechanisms:
#IndexFlatIP → brute-force search with inner product (good for normalized cosine similarity).
#IVF (Inverted File Index) → approximate search, much faster for millions of vectors.
#HNSW / PQ → advanced graph/quantization methods for billion-scale datasets
#For our project, (as you see later, when you scroll down, the #vectors are ~16500). So indexFlatIP would work.
#If the indexes were more than a million, then there is a need to switch to IVF or HNSW.
#Decision Making Factor - #DMF
index = faiss.IndexFlatIP(vec_dim)

# Mapping from index row -> chunk metadata (kept on disk)
meta_jsonl_path = DIR_META / "chunks_meta.jsonl"
open(meta_jsonl_path, "w").close()  # reset

def normalize(vecs: np.ndarray) -> np.ndarray:
    norms = np.linalg.norm(vecs, axis=1, keepdims=True) + 1e-12
    return vecs / norms

def chunk_text(text, size=CHUNK_SIZE, overlap=CHUNK_OVERLAP):
    # simple character-based chunking
    chunks = []
    start = 0
    L = len(text)
    while start < L:
        end = min(L, start + size)
        chunks.append(text[start:end])
        if end >= L: break
        start = end - overlap
        if start < 0: start = 0
    return chunks

def safe_filename(s: str) -> str:
    return re.sub(r'[^A-Za-z0-9_\-]+', '_', s).strip("_")

"""###**Vishwa: Warning: One time ingestion code that writes onto Disk**
###** RUN ONLY ONCE . DO NOT EXECUTE THIS REPEATEDLY. ITS GONNA COST YOU $$$ TPU**
"""

row_id = 0
with pdfplumber.open(str(pdf_fullpath)) as pdf:  # keep open to reduce overhead
    for sect_title, (p_start, p_end) in tqdm(section_ranges.items(), desc="Sections"):
        # Collect section text page-by-page (but never keep too many in RAM)
        section_text_parts = []
        for p in range(p_start-1, p_end):
            txt = page_text_cached(p)  # cached
            # Mark page boundaries inside chunk text (for citations)
            section_text_parts.append(f"\n[[PAGE {p+1}]]\n{txt}")

            # flush sometimes to reduce RAM
            if (p - (p_start-1) + 1) % BATCH_PDF_PAGES == 0:
                pass

        section_text = "\n".join(section_text_parts)
        # basic whitespace cleanup
        section_text = re.sub(r'[ \t]+', ' ', section_text)
        section_text = re.sub(r'\n{3,}', '\n\n', section_text)

        # Chunk the section
        chunks = chunk_text(section_text, CHUNK_SIZE, CHUNK_OVERLAP)

        # Write chunks for this section to disk and embed in batches
        # (so we never keep too many in memory)
        for i in range(0, len(chunks), BATCH_EMBED):
            batch = chunks[i:i+BATCH_EMBED]

            # Persist each chunk to disk first (one file per chunk)
            chunk_paths = []
            for j, c in enumerate(batch):
                chunk_name = f"{safe_filename(sect_title)[:80]}__{i+j:06d}.txt"
                cpath = DIR_CHUNKS / chunk_name
                cpath.write_text(c, encoding="utf-8")
                chunk_paths.append(cpath)

            # Embed this batch
            embs = emb_model.encode(
                batch, batch_size=min(32, len(batch)), show_progress_bar=False, normalize_embeddings=True
            ).astype("float32")

            # Add to FAISS
            index.add(embs)

            # Write metadata lines (row-wise mapping)
            with open(meta_jsonl_path, "a", encoding="utf-8") as mfh:
                for j, cpath in enumerate(chunk_paths):
                    # Extract page hints for citation
                    pages = re.findall(r"\[\[PAGE (\d+)\]\]", batch[j])
                    cite = f"p. {pages[0]}–{pages[-1]}" if len(pages) > 1 else (f"p. {pages[0]}" if pages else f"p. {p_start}–{p_end}")
                    payload = {
                        "row_id": row_id,
                        "chunk_path": str(cpath),
                        "section_title": sect_title,
                        "section_pages": [p_start, p_end],
                        "citation": cite
                    }
                    mfh.write(json.dumps(payload, ensure_ascii=False) + "\n")
                    row_id += 1

            # Free memory
            del embs, batch
            gc.collect()

# Save FAISS + model name
faiss.write_index(index, str(DIR_INDEX / "faiss.index"))
(DIR_INDEX / "embed_model.txt").write_text(EMBED_MODEL_NAME)
print("✅ Finished indexing.")
print(f"Total vectors: {index.ntotal}")

"""### Data Chunking:

Rebuidling chunks_meta.jsonl : Run this code each time, when you start Google Colab, to rebuild the chunks
 - Section that rebuilds chunks_meta.jsonl, by scanning the files under 'chunks'/folder.
 - Run this code section only if you have lost the chunks_meta.jsonl file. This will rebuild the chunks.The chunks file gets reset, each time you close Google colab.
"""

import json
import re
from pathlib import Path
from tqdm import tqdm

# The below paths are defined above already. Just for reference.
#Base_Dir = Path("/content/drive/MyDrive")
#DIR_PAGES   = Base_Dir / "pages_text"   # per-page text (OCR/normal)
#DIR_CHUNKS  = Base_Dir / "chunks"       # individual chunk .txt files
#DIR_META    = Base_Dir / "meta"         # mapping/jsonl
#DIR_INDEX   = Base_Dir / "index"        # FAISS index + model name

# Readujsting the paths here, that are present in your Google drive
DIR_CHUNKS  = Base_Dir / "chunks"
meta_jsonl_path = DIR_META / "chunks_meta.jsonl"

# Start fresh
if meta_jsonl_path.exists():
    print("⚠️ Existing metadata file found, backing up...")
    meta_jsonl_path.rename(meta_jsonl_path.with_suffix(".bak"))

row_id = 0
with open(meta_jsonl_path, "w", encoding="utf-8") as mfh:
    for cpath in tqdm(sorted(DIR_CHUNKS.glob("*.txt")), desc="Rebuilding metadata"):
        text = cpath.read_text(encoding="utf-8")

        # Extract page markers if present
        pages = re.findall(r"\[\[PAGE (\d+)\]\]", text)
        if len(pages) > 1:
            cite = f"p. {pages[0]}–{pages[-1]}"
        elif len(pages) == 1:
            cite = f"p. {pages[0]}"
        else:
            cite = "unknown pages"

        payload = {
            "row_id": row_id,
            "chunk_path": str(cpath),
            "section_title": "unknown",   # lost since jsonl was deleted
            "section_pages": [int(pages[0]), int(pages[-1])] if pages else [],
            "citation": cite,
        }
        mfh.write(json.dumps(payload, ensure_ascii=False) + "\n")
        row_id += 1

print(f"✅ Done. Rebuilt metadata for {row_id} chunks into {meta_jsonl_path}")

"""##Lightweight retrieval (loads index + streams chunk text from disk)

###The following piece of code can be run after the ingestion is complete. The following piece of code is only a retrieval snippet that loads the FAISS index
"""

# Load for querying
index = faiss.read_index(str(DIR_INDEX / "faiss.index"))
EMBED_MODEL_NAME = (DIR_INDEX / "embed_model.txt").read_text().strip()
emb_model = SentenceTransformer(EMBED_MODEL_NAME)

# Lazy load metadata into a list (row_id -> meta)
meta = []
with open(meta_jsonl_path, "r", encoding="utf-8") as f:
    for line in f:
        meta.append(json.loads(line))
print(f"Loaded metadata for {len(meta)} chunks")

"""**Retriever function**"""

#The following function retrieves using FAISS search
def retrieve(query: str, k: int = TOP_K):
    q = emb_model.encode([query], normalize_embeddings=True).astype("float32")
    D, I = index.search(q, k)
    I = I[0].tolist()
    D = D[0].tolist()
    results = []
    for rank, (row, score) in enumerate(zip(I, D)):
        m = meta[row]
        text = Path(m["chunk_path"]).read_text(encoding="utf-8", errors="ignore")[:2000]  # cap display length
        results.append({
            "rank": rank+1,
            "score": float(score),
            "citation": m["citation"],
            "section": m["section_title"],
            "chunk_path": m["chunk_path"],
            "preview": text[:600].strip().replace("\n", " ")  # short preview
        })
    return results

# Quick test for retrieval only
for r in retrieve("Treatment for iron deficiency anemia", k=5):
    print(f"[{r['rank']}] {r['section']} | {r['citation']} | score={r['score']:.3f}")
    print(r["preview"], "\n")

"""##Data Overview

##Helper Sections
"""

from pathlib import Path
import json, re, os, torch

#Libraries for downloading and loading the llm
from huggingface_hub import hf_hub_download
from llama_cpp import Llama

from contextlib import redirect_stdout, redirect_stderr

# Example repo/filename (adjust to what you choose on HF)
#repo_id  = "Qwen/Qwen2.5-3B-Instruct-GGUF"
#filename = "qwen2.5-3b-instruct-q4_k_m.gguf"  # Vishwa: This model did not work. Compability with 0.1.85 becomes a problem and you get into many library compatibility issues. So sticking to the libraries suggested for this project.


repo_id  = "TheBloke/Llama-2-7B-Chat-GGUF"
filename = "llama-2-7b-chat.Q4_0.gguf"  # classic quant compatible with 0.1.85

model_path = hf_hub_download(repo_id=repo_id, filename=filename)
print("GGUF model:", model_path)

has_cuda = torch.cuda.is_available()
print("CUDA:", has_cuda)

#Vishwa: The devnull wrapping is needed only with Google Colab.  The progress is written to a log file whose .fileno() is not supported by Colab notebook.
## Suppress llama.cpp's C++ stdout/stderr noise in Colab
# (optional) also mute llama logs

def try_offload(n_gpu_layers):
    with open(os.devnull, "w") as devnull:
        with redirect_stdout(devnull), redirect_stderr(devnull):
            m = Llama(
                model_path=model_path,
                n_ctx=4096,
                n_threads=max(1, os.cpu_count()-1),
                n_gpu_layers=n_gpu_layers,
                use_mmap=True,
                verbose=False,
                # Tweaks that help on some T4 builds:
                # mul_mat_q=False,          # uncomment if you see CUDA matmul issues
                # low_vram=True,            # can help with tight VRAM
            )
    return m

llm = None
if has_cuda:
    for n in [16, 32, 48, 64, -1]:   # 3B q4_k_m should handle -1 on T4, but step up safely
        try:
            llm = try_offload(n)
            print(f"✅ Loaded with n_gpu_layers={n}")
            break
        except Exception as e:
            print(f"❌ n_gpu_layers={n} failed: {type(e).__name__}: {e}")

if llm is None:
    # fallback to CPU if all GPU attempts failed (shouldn’t happen on T4 + 3B q4_k_m)
    print("Falling back to CPU-only model (n_gpu_layers=0).")
    llm = try_offload(0)

resp = llm.create_chat_completion(
    messages=[
        {"role":"system","content":"You are a concise clinical assistant."},
        {"role":"user","content":"Name two initial actions in suspected sepsis."}
    ],
    max_tokens=64,
    temperature=0.0,
)
print(resp["choices"][0]["message"]["content"])

def _generate_chat(messages, max_tokens=512, temperature=0.0, top_p=0.95, top_k=50, stop=None):
    """
    messages: list of {'role': 'system'|'user'|'assistant', 'content': '...'}
    returns: assistant string
    """
    res = llm.create_chat_completion(
        messages=messages,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        stop=stop,  # e.g., stop=["</s>"] if you see trailing artifacts
    )
    return res["choices"][0]["message"]["content"].strip()

def _clean_after_tag(text: str, tag: str = "Answer:"):
    return text.split(tag, 1)[-1].strip() if tag in text else text.strip()

def _build_context_from_hits(hits, max_chars_per_chunk=1800):
    """Build a numbered context block + a printable sources list from your retrieve() hits."""
    ctx_lines, sources = [], []
    for i, h in enumerate(hits, start=1):
        chunk_text = Path(h["chunk_path"]).read_text(encoding="utf-8", errors="ignore")
        if len(chunk_text) > max_chars_per_chunk:
            chunk_text = chunk_text[:max_chars_per_chunk]
        src_label = f"{Path(h['chunk_path']).name} · {h.get('section','unknown')} · {h.get('citation','')}"
        ctx_lines.append(f"[{i}] Source: {src_label}\n{chunk_text.strip()}")
        sources.append({"n": i, "path": h["chunk_path"], "section": h.get("section","unknown"), "citation": h.get("citation","")})
    return "\n\n".join(ctx_lines), sources

"""##Queries consolidated"""

#All the queries have been summarized into this structure
queries = [
    "What is the protocol for managing sepsis in a critical care unit?"
    "What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"
    "What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"
    "What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"
    "What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?"
]

"""## Question Answering using LLM

#### Downloading and Loading the model
"""

def qa_llm_only(question: str, max_tokens=400):
    messages = [
        {"role": "system", "content": "You are a helpful, concise clinical assistant. If unsure, say so."},
        {"role": "user", "content": question},
    ]
    return _generate_chat(messages, max_tokens=max_tokens, temperature=0.0)

"""#### Response"""

def response(query,max_tokens=128,temperature=0,top_p=0.95,top_k=50):
    model_output = llm(
      prompt=query,
      max_tokens=max_tokens,
      temperature=temperature,
      top_p=top_p,
      top_k=top_k
    )

    return model_output['choices'][0]['text']

"""### Query 1: What is the protocol for managing sepsis in a critical care unit?"""

print(qa_llm_only("What is the protocol for managing sepsis in a critical care unit?"))

"""### Query 2: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"""

print(qa_llm_only("What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"))

"""### Query 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"""

print(qa_llm_only("What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"))

"""### Query 4:  What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"""

print(qa_llm_only("What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"))

"""### Query 5: What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?"""

print(qa_llm_only("What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?"))

"""## Question Answering using LLM with Prompt Engineering"""

PE_SYSTEM = (
    "You are a cautious clinical assistant. Be concise, medically accurate, and avoid speculation.\n"
    "If you are not confident or the question requires external references, say you don't have enough information."
)

PE_GUIDELINES = (
     "Task: Answer the user’s clinical question.\n"
    "Requirements:\n"
    "• Use short bullets.\n"
    "• Include first-line steps, monitoring, red flags, and follow-up if relevant.\n"
    "• If uncertain, explicitly say so.\n\n"
    "Question: {question}\n"
    "Answer:"
)

def qa_llm_prompt_engineered(question: str, max_new_tokens=350):
    messages = [
        {"role": "system", "content": PE_SYSTEM},
        {"role": "user",   "content": PE_GUIDELINES.format(question=question)},
    ]
    return _generate_chat(messages, max_tokens=max_new_tokens, temperature=0.0)

"""### Query 1: What is the protocol for managing sepsis in a critical care unit?"""

print(qa_llm_prompt_engineered("What is the protocol for managing sepsis in a critical care unit?"))

"""### Query 2: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"""

print(qa_llm_prompt_engineered("What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"))

"""### Query 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"""

print(qa_llm_prompt_engineered("What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"))

"""### Query 4:  What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"""

print(qa_llm_prompt_engineered("What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"))

"""### Query 5: What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?"""

print(qa_llm_prompt_engineered("What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?"))

"""## Data Preparation for RAG"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# Choose a small model that runs on CPU; if you have GPU, we’ll auto-use it.
# Good starting points:
#   CPU:  TinyLlama/TinyLlama-1.1B-Chat-v1.0  (very small, basic quality)
#   GPU:  Qwen/Qwen2.5-3B-Instruct            (better quality; 4-bit fits on Colab GPU. But mind you, not compatible with the llama-cpp-python version that is suggested.
#Lets stick to the library compatible version predicted in this project.

HF_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

#Detects GPU availability. We do use GPU & TPU here. Using TPU to create the index files anyway
use_4bit = torch.cuda.is_available() and ("Qwen2.5" in HF_MODEL or "Qwen" in HF_MODEL)

#/AutoTokenizer loads the correct tokenizer for the model. Essentially handles tokenization and decoding
tokenizer = AutoTokenizer.from_pretrained(HF_MODEL)

#AutoModeForCausalLLM loads the causal language model that predicts the next tokens
if use_4bit:
    model = AutoModelForCausalLM.from_pretrained(
        HF_MODEL,
        device_map="auto",
        torch_dtype="auto",
        load_in_4bit=True,
    )
else:
    model = AutoModelForCausalLM.from_pretrained(
        HF_MODEL,
        device_map="auto",
        torch_dtype="auto",
    )

#pipeline wraps the model + tokenizer into a simple text generation interface
gen = pipeline("text-generation", model=model, tokenizer=tokenizer)
print("Model loaded:", HF_MODEL, "| 4-bit:", use_4bit, "| CUDA:", torch.cuda.is_available())

"""### Response Function

Building the RAG wrapper

Feeds the retrieved chunks into a local LLM
"""

from pathlib import Path

def qa_rag_llama(question: str, k: int = 6, score_floor: float = 0.25, max_new_tokens=480):
    hits = retrieve(question, k=k)
    hits = [h for h in hits if h.get("score", 0.0) >= score_floor]
    if not hits:
        return "I don’t have enough information in the retrieved context to answer this.", []

    #Vishwa: This is where we build the context from the Merck Manual
    try:
        context_block, sources = _build_context_from_hits(hits, max_chars_per_chunk=1800)
    except NameError:
        from pathlib import Path
        ctx_lines, sources = [], []
        for i, h in enumerate(hits, start=1):
            chunk_text = Path(h["chunk_path"]).read_text(encoding="utf-8", errors="ignore")
            if len(chunk_text) > 1800: chunk_text = chunk_text[:1800]
            src_label = f"{Path(h['chunk_path']).name} · {h.get('section','unknown')} · {h.get('citation','')}"
            ctx_lines.append(f"[{i}] Source: {src_label}\n{chunk_text.strip()}")
            sources.append({"n": i, "path": h["chunk_path"], "section": h.get("section","unknown"), "citation": h.get("citation","")})
        context_block = "\n\n".join(ctx_lines)

    sys_msg = ("You are a cautious clinical assistant. Answer ONLY using the CONTEXT. "
               "Use inline citations like [n] that refer to the numbered sources. "
               "If the answer is not fully supported by CONTEXT, say you don’t have enough information.")
    user_msg = f"CONTEXT:\n{context_block}\n\nQUESTION:\n{question}\n\nANSWER (with inline [n] citations):"
    messages = [
        {"role": "system", "content": sys_msg},
        {"role": "user",   "content": user_msg},
    ]
    answer = _generate_chat(messages, max_tokens=max_new_tokens, temperature=0.0)
    return answer, sources

"""## Question Answering using RAG"""

from pathlib import Path

def print_sources(sources):
    for s in sources:
        print(f"[{s['n']}] {Path(s['path']).name} | {s.get('section','unknown')} | {s.get('citation','')}")

"""### Query 1: What is the protocol for managing sepsis in a critical care unit?"""

ans, srcs = qa_rag_llama("What is the protocol for managing sepsis in a critical care unit?")
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)

"""### Query 2: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"""

ans, srcs = qa_rag_llama("What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?")
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)

"""### Query 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"""

ans, srcs = qa_rag_llama("What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?")
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)

"""### Query 4:  What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"""

ans, srcs = qa_rag_llama("What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?")
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)

"""### Query 5: What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?"""

ans, srcs = qa_rag_llama("What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?")
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)

"""## Output Evaluation

Let us now use the LLM-as-a-judge method to check the quality of the RAG system on two parameters - retrieval and generation. We illustrate this evaluation based on the answeres generated to the question from the previous section.

- We are using the same Mistral model for evaluation, so basically here the llm is rating itself on how well he has performed in the task.
"""

qna_system_message = (
    "You are a cautious clinical assistant. Answer ONLY from the provided CONTEXT. "
    "Use inline [n] citations where possible. If information is missing, say so."
)
qna_user_message_template = "CONTEXT:\n{context}\n\nQUESTION:\n{question}\n\nANSWER:"

groundedness_rater_system_message  = """\
You are a strict scientific evaluator. Rate how well the ANSWER is grounded in the provided CONTEXT.
Rules:
- Consider only information present in CONTEXT as valid support.
- Penalize any claims not supported by CONTEXT.
Return ONLY a JSON object: {"score": <0-5>, "justification": "<1-2 sentences>"}.
Scoring:
0: not grounded; 1: mostly unsupported; 2: partial; 3: mostly grounded; 4: well grounded; 5: fully grounded.
"""

relevance_rater_system_message = """\
You are an IR evaluator. Rate how relevant the CONTEXT is for answering the QUESTION.
- Judge topical match and whether key facts are present.
Return ONLY a JSON object: {"score": <0-5>, "justification": "<1-2 sentences>"}.
Scoring:
0=irrelevant; 1=barely; 2=partial; 3=moderate; 4=high; 5=perfect.
"""

user_message_template = """\
CONTEXT:
{context}

QUESTION:
{question}

ANSWER:
{answer}

Provide your evaluation per instructions."""

from pathlib import Path

def generate_ground_relevance_response(user_input, k=3, max_tokens=200, temperature=0.0):
    """
    Returns:
      groundedness_text_json, relevance_text_json, answer_text
    - Uses FAISS `retrieve(...)` to build CONTEXT
    - Uses llama_cpp via `_generate_chat(...)`
    """
    global qna_system_message, qna_user_message_template
    global groundedness_rater_system_message, relevance_rater_system_message, user_message_template

    # --- Retrieve relevant chunks from FAISS ---
    hits = retrieve(user_input, k=k)  # each hit: {chunk_path, section, citation, score, ...}

    # --- Build a bounded CONTEXT from file contents ---
    MAX_CHARS_PER_CHUNK = 1500
    MAX_CONTEXT_CHARS   = 6000
    context_parts, total = [], 0

    for h in hits:
        try:
            t = Path(h["chunk_path"]).read_text(encoding="utf-8", errors="ignore").strip()
        except Exception:
            t = ""
        if not t:
            continue
        t = t[:MAX_CHARS_PER_CHUNK]
        if total + len(t) > MAX_CONTEXT_CHARS:
            break
        context_parts.append(t)
        total += len(t)

    context_for_query = "\n\n".join(context_parts) if context_parts else "(no relevant context retrieved)"

    # --- Produce the answer to be judged (RAG-style) ---
    qna_messages = [
        {"role": "system", "content": qna_system_message},
        {"role": "user",   "content": qna_user_message_template.format(
            context=context_for_query, question=user_input
        )},
    ]
    # llama_cpp chat (deterministic for evaluation)
    answer_text = _generate_chat(qna_messages, max_tokens=max_tokens, temperature=temperature)

    # --- Judges: GROUNDEDNESS ---
    grounded_msgs = [
        {"role": "system", "content": groundedness_rater_system_message},
        {"role": "user",   "content": user_message_template.format(
            context=context_for_query, question=user_input, answer=answer_text
        )},
    ]
    groundedness_text = _generate_chat(grounded_msgs, max_tokens=160, temperature=0.0)

    # --- Judges: RELEVANCE ---
    relevance_msgs = [
        {"role": "system", "content": relevance_rater_system_message},
        {"role": "user",   "content": user_message_template.format(
            context=context_for_query, question=user_input, answer=answer_text
        )},
    ]
    relevance_text = _generate_chat(relevance_msgs, max_tokens=160, temperature=0.0)

    return groundedness_text, relevance_text, answer_text

"""### Query 1: What is the protocol for managing sepsis in a critical care unit?"""

question = "What is the protocol for managing sepsis in a critical care unit?"
ans, srcs = qa_rag_llama(question, k=6, score_floor=0.25, max_new_tokens=650)
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)

# --- Run LLM-as-a-Judge evaluation ---
groundedness_text, relevance_text, answer_text = generate_ground_relevance_response(
    question, k=3, max_tokens=200, temperature=0.0
)

#groundedness_text, relevance_text
print("\n--- JUDGE: GROUNDEDNESS ---")
print(groundedness_text)
print("\n--- JUDGE: RELEVANCE ---")
print(relevance_text)

"""### Query 2: What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"""

question = "What are the common symptoms for appendicitis, and can it be cured via medicine? If not, what surgical procedure should be followed to treat it?"

ans, srcs = qa_rag_llama(question, k=6, score_floor=0.25, max_new_tokens=650)
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)

# --- Run LLM-as-a-Judge evaluation ---
groundedness_text, relevance_text, answer_text = generate_ground_relevance_response(
    question, k=3, max_tokens=200, temperature=0.0
)

#groundedness_text, relevance_text
print("\n--- JUDGE: GROUNDEDNESS ---")
print(groundedness_text)
print("\n--- JUDGE: RELEVANCE ---")
print(relevance_text)

"""### Query 3: What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"""

question = "What are the effective treatments or solutions for addressing sudden patchy hair loss, commonly seen as localized bald spots on the scalp, and what could be the possible causes behind it?"
ans, srcs = qa_rag_llama(question, k=6, score_floor=0.25, max_new_tokens=650)
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)


# --- Run LLM-as-a-Judge evaluation ---
groundedness_text, relevance_text, answer_text = generate_ground_relevance_response(
    question, k=3, max_tokens=200, temperature=0.0
)

#groundedness_text, relevance_text
print("\n--- JUDGE: GROUNDEDNESS ---")
print(groundedness_text)
print("\n--- JUDGE: RELEVANCE ---")
print(relevance_text)

"""### Query 4: What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"""

question = "What treatments are recommended for a person who has sustained a physical injury to brain tissue, resulting in temporary or permanent impairment of brain function?"

ans, srcs = qa_rag_llama(question, k=6, score_floor=0.25, max_new_tokens=650)
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)

# --- Run LLM-as-a-Judge evaluation ---
groundedness_text, relevance_text, answer_text = generate_ground_relevance_response(
    question, k=3, max_tokens=200, temperature=0.0
)

#groundedness_text, relevance_text
print("\n--- JUDGE: GROUNDEDNESS ---")
print(groundedness_text)
print("\n--- JUDGE: RELEVANCE ---")
print(relevance_text)

"""### Query 5: What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?"""

question = "What are the necessary precautions and treatment steps for a person who has fractured their leg during a hiking trip, and what should be considered for their care and recovery?"

ans, srcs = qa_rag_llama(question, k=6, score_floor=0.25, max_new_tokens=650)
print("\n--- ANSWER ---")
print(ans)
print("\n--- SOURCES ---")
print_sources(srcs)

# --- Run LLM-as-a-Judge evaluation ---
groundedness_text, relevance_text, answer_text = generate_ground_relevance_response(
    question, k=3, max_tokens=200, temperature=0.0
)

#groundedness_text, relevance_text
print("\n--- JUDGE: GROUNDEDNESS ---")
print(groundedness_text)
print("\n--- JUDGE: RELEVANCE ---")
print(relevance_text)

"""## Actionable Insights and Business Recommendations

The RAG model built here, speedens up, automates and speedens up the initial responses that the patients may have . Several aspects to this:


**BUSINESS RECOMMENDATIONS:**

**Clinical Safety and Governance:**
  
*   **Human in the loop:** The inferences, responses must be reviewed and okayed by a human being. It should not be used for any further surgical, medical decisions
*   **Strict Grounding**: Answers having citing sources and with relevance atleast of '3 and Groundedness atleast of '3' can be allowed


**Decision Support, Not Decision Making:** Position the system as an assistant that augments clinicians, not replaces them. This ensures trust and regulatory compliance

**Patient-facing Modules::** Extend the system to provide simplified, plain-language educational summaries from trusted sources (e.g., Merck Manual consumer edition). This reduces staff time spent on explaining basics.

**Domain-specific Playbooks:** Develop “playbooks” for high-impact conditions (sepsis bundle, stroke management, myocardial infarction protocols, etc.) so clinicians can quickly pull standardized, guideline-based steps.

**Market Differentiation:** Position the solution as trusted, grounded, source-cited clinical AI — differentiating it from generic chatbots.

**Data Residency:** Host FAISS index + LLM inference in-country (e.g., within the Netherlands/EU) to comply with GDPR.


**Scalability & Expansion**

**Multilingual Support:** Extend embeddings + LLM to Dutch, German, and French (for EU hospitals).

**Cross-domain Expansion:** After success in critical care, scale into pharmacy, nursing education, insurance claim review, etc.

**Commercial Offering:** Position as a Healthcare Knowledge Assistant Platform with modular connectors for different medical manuals, EHR systems, and languages.

**ACTIONABLE INSIGHTS:**

**Evaluation via LLM-as-a-Judge Identifies Gaps**

The groundedness and relevance evaluation highlighted cases where the LLM generated plausible but unsupported claims if the retrieved context was insufficient.

This confirms the need for context filtering (score_floor) and source transparency in clinical use cases.

Insight: Automating this evaluation loop helps track model reliability and can serve as a quality monitoring dashboard in production.

**Indexing at Scale is Feasible with Compute Units**

The Merck Manual (4,000+ pages) was successfully embedded and indexed on Colab with TPU support (using ~15 compute units).

Streaming chunking + batch embeddings allowed ingestion without memory crashes.

Insight: With this approach, large medical references can be made queryable without requiring continuous API costs, enabling scalable deployment in hospitals.


**Model Choice Impacts Quality & Cost**

TinyLlama (1.1B): lightweight, CPU-friendly, but produced incomplete/truncated answers.

Qwen2.5-3B (GGUF with llama-cpp): higher quality, better context handling, but requires GPU/TPU for reasonable latency.

Insight: Hybrid strategy — use small models locally for triage/basic queries, and larger models (Qwen, Mistral, or GPT-4o) for complex diagnostic/treatment questions.
"""