# -*- coding: utf-8 -*-
"""Vishwa_NLP_LLM_SentimentAnalysis_Project_Full_Code_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10kevU9-SPl64VO5uJPeQ6_wuLBKMezgn

## **Problem Statement**

### Business Context

The prices of the stocks of companies listed under a global exchange are influenced by a variety of factors, with the company's financial performance, innovations and collaborations, and market sentiment being factors that play a significant role. News and media reports can rapidly affect investor perceptions and, consequently, stock prices in the highly competitive financial industry. With the sheer volume of news and opinions from a wide variety of sources, investors and financial analysts often struggle to stay updated and accurately interpret its impact on the market. As a result, investment firms need sophisticated tools to analyze market sentiment and integrate this information into their investment strategies.

### Problem Definition

With an ever-rising number of news articles and opinions, an investment startup aims to leverage artificial intelligence to address the challenge of interpreting stock-related news and its impact on stock prices. They have collected historical daily news for a specific company listed under NASDAQ, along with data on its daily stock price and trade volumes.

As a member of the Data Science and AI team in the startup, you have been tasked with analyzing the data, developing an AI-driven sentiment analysis system that will automatically process and analyze news articles to gauge market sentiment, and summarizing the news at a weekly level to enhance the accuracy of their stock price predictions and optimize investment strategies. This will empower their financial analysts with actionable insights, leading to more informed investment decisions and improved client outcomes.

### Data Dictionary

* `Date` : The date the news was released
* `News` : The content of news articles that could potentially affect the company's stock price
* `Open` : The stock price (in \$) at the beginning of the day
* `High` : The highest stock price (in \$) reached during the day
* `Low` :  The lowest stock price (in \$) reached during the day
* `Close` : The adjusted stock price (in \$) at the end of the day
* `Volume` : The number of shares traded during the day
* `Label` : The sentiment polarity of the news content
    * 1: positive
    * 0: neutral
    * -1: negative

## **Installing and Importing Necessary Libraries**
"""

#Vishwa
import sys
import os
import time
import numpy as np
# Importing the library for data manipulation
import pandas as pd

# to visualise data
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
# To import Word2Vec
from gensim.models import Word2Vec

# To tune the model
from sklearn.model_selection import GridSearchCV

# Converting the Stanford GloVe model vector format to word2vec
from gensim.scripts.glove2word2vec import glove2word2vec
from gensim.models import KeyedVectors
import torch
from sentence_transformers import SentenceTransformer

# to split data into train and test sets
from sklearn.model_selection import train_test_split
# to build a Random Forest model
from sklearn.ensemble import RandomForestClassifier
# to compute metrics to evaluate the model
from sklearn import metrics
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix

# installing libraries to use word embeddings
!pip install gensim -q
# installing the sentence-transformers and gensim libraries for word embeddings
!pip install -U sentence-transformers gensim transformers tqdm -q

# Ensure required NLTK data is downloaded
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

# to load the natural language toolkit
nltk.download('wordnet')    # loading the wordnet module that is used in stemming

"""## **Loading the dataset**"""

# loading the dataset
from google.colab import drive
drive.mount('/content/drive')
#VC Added
os.chdir("/content/drive/MyDrive")

#Read the file
data_original = pd.read_csv("stock_news.csv")

data = data_original.copy()
# let's view a sample of the data
data.sample(n=10, random_state=42)

"""## **Data Overview**"""

data.info()

"""

- Out of the 7 columns present in the dataset, 2 of them are objects while the other 6 of them are numerical in nature
- There are no missing values, since all the parameters have values
- There is a need to convert Date field into a 'Datetime' format

"""

# Convert 'Date' column to datetime format
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

# Drop rows with invalid dates
data = data.dropna(subset=['Date'])

# Sort data by Date
data = data.sort_values(by='Date')

data.isnull().sum()
# let's check for missing values in the data
round(data.isnull().sum() / data.isnull().count() * 100, 2)

# let's check for duplicate values in the data
data.duplicated().sum()

data.describe().T

label_distribution = data['Label'].value_counts()
print(label_distribution)

"""Data Summary:

  Total rows: 349.
  - All columns are complete, with no missing values.
  - Date is successfully converted to datetime64[ns].(the formatted data)
  - The price range of all the stocks aggregated is in the range of  37 - 67 dollars
  - The volumes range from 45 million to around 2.4 billion trades

Sentiment Distribution:
  The sentiment distribution label, when examined has this distribution

  - Neutral (Label 0): 170 entries.
  - Negative (Label -1): 99 entries.
  - Positive  (Label 1): 80 entries.

Lets just observe the length of the entire news on the specific stocks
"""

data['news_length'] = data['News'].apply(lambda x: len(x.split(' ')))
data['news_length'].describe()

columns = ['Open', 'High', 'Low', 'Close', 'Volume', 'news_length']

# Compute the correlation matrix
correlation_matrix = data[columns].corr()
plt.figure(figsize=(5,5))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Matrix of the Stock data')
plt.show()

"""- There is minimal take away from the above correlation matrix except for one key aspect: Volume seems to be inversely correlated to 'Low' stock price(correlation is -0.1) This implies that if the stock price is hitting low, then the volumes have been high - owing to selling pressure. This makes perfect sense

###Data Cleansing and pre-processing

There could be a need to remove special characters, subsequently. Right now, we will only clean it and keep. We may or may not need this function
"""

import re

def clean_text(text):

    # Lowercase the text
    text = text.lower()

    # Remove punctuation and special characters
    pattern = '[^A-Za-z0-9\w\s+]'
    text = re.sub(pattern, '', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply the cleaning function to the News column
data['Cleaned_News'] = data['News'].apply(clean_text)

# Preview the cleaned data
data[['News', 'Cleaned_News']].head(10)

data.head()

data.info()

"""## **Exploratory Data Analysis**"""

# Lets map the sentiments to a more meaningful column
sentiment_mapping = {-1: 'Negative', 0: 'Neutral', 1: 'Positive'}
# Apply the mapping to the 'Label' column
data['Sentiment'] = data['Label'].map(sentiment_mapping)
# Check the updated DataFrame
print(data.head())

"""### Univariate Analysis

* Distribution of individual variables
* Compute and check the distribution of the length of news content
"""

# Plot the distribution of the Label column
plt.figure(figsize=(6, 4))
sns.countplot(data=data, x='Sentiment')
plt.title('Distribution of Sentiment Labels')
plt.xlabel('Sentiment Label')
plt.ylabel('Count')
plt.xticks(ticks=[0, 1, 2], labels=['Negative (-1)', 'Neutral (0)', 'Positive (1)'])
plt.show()

data_cleaned = data.copy()
# Compute the length of each news article
data_cleaned['News_Length'] = data['News'].apply(len)

# Check basic statistics of the news lengths
print(data_cleaned['News_Length'].describe())

# Plot the distribution of news lengths
plt.figure(figsize=(10, 6))
sns.histplot(data_cleaned['News_Length'], bins=30, kde=True, color='blue')
plt.title('Distribution of News Content Length')
plt.xlabel('Length of News Content')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

"""- As we see the average length of new contents is about 302 letters, while the maximum is about 390."""

sns.boxplot(data=data, x='Sentiment', y='Volume')

"""### Bivariate Analysis

* Correlation
* Sentiment Polarity vs Price
* Date vs Price

**Note**: The above points are listed to provide guidance on how to approach bivariate analysis. Analysis has to be done beyond the above listed points to get maximum scores.
"""

# Plot Open and Close prices over time
plt.figure(figsize=(12, 6))
plt.plot(data['Date'], data['Open'], label='Open Price', color='blue')
plt.plot(data['Date'], data['Close'], label='Close Price', color='green')
plt.title('Stock Prices Over Time')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.show()

"""## **Data Preprocessing**

## Word Embeddings

For Sentiment analysis, and to understand the data distribution across the months, lets analyze the aggregated words together.
Lets examine the column - 'Date' based on which we would know how the data is spread across various timelines
"""

data['Date'].describe()

""" - What you see here is - 75% of the data is available on or before March 22, 2019, while the remaining 25% of the data is spread between 23 March till 30th April 2019.
 -Lets use this to split the data 75% Training and the rest of 25% as Test and Validation data
"""

X_train = data[data['Date'] < '2019-03-22'].reset_index()
X_val = data[(data['Date'] >= '2019-03-22') & (data['Date'] < '2019-04-08')].reset_index()
X_test = data[data['Date'] >= '2019-04-08'].reset_index()

y_train = X_train['Label'].copy()
y_val = X_val['Label'].copy()
y_test = X_test['Label'].copy()

# Check the shape of the splits
print(f'Training set shape: {X_train.shape}')
print(f'Validation set shape: {X_val.shape}')
print(f'Test set shape: {X_test.shape}')

# Check the shape of the splits
print(f'Training set shape: {y_train.shape}')
print(f'Validation set shape: {y_val.shape}')
print(f'Test set shape: {y_test.shape}')

y_train.value_counts(normalize=True)

y_val.value_counts(normalize=True)

"""- From the above , as expected the 'Neutral' values are high. The positive and negatives are low. Implying - not a good data set, OR a larger data set is the need of the hour.
- Anyway, this is what is given for the Project, So  - lets do it.

### **Word2Vec**
"""

# Creating a list of all words in our data
words_list = [item.split(" ") for item in data['News'].values]

# Creating an instance of Word2Vec
vec_size = 300
model_W2V = Word2Vec(words_list, vector_size = vec_size, min_count = 1, window=5, workers = 6)

# Checking the size of the vocabulary
print("Length of the vocabulary is", len(list(model_W2V.wv.key_to_index)))

# Checking the word embedding of a random word that has occured in our data sentence
word = "dollar"
model_W2V.wv[word]

similar = model_W2V.wv.similar_by_word('price', topn=5)
print(similar)

# Checking the word embedding of a random word that has occured in our data sentence
word = "trade"
model_W2V.wv[word]

"""Lets retrieve all the words present in the Word2Vec model's vocab"""

# Retrieving the words present in the Word2Vec model's vocabulary
words = list(model_W2V.wv.key_to_index.keys())

# Retrieving word vectors for all the words present in the model's vocabulary
wvs = model_W2V.wv[words].tolist()

# Creating a dictionary of words and their corresponding vectors
word_vector_dict = dict(zip(words, wvs))

def average_vectorizer_Word2Vec(doc):
    # Initializing a feature vector for the sentence
    feature_vector = np.zeros((vec_size,), dtype="float64")

    # Creating a list of words in the sentence that are present in the model vocabulary
    words_in_vocab = [word for word in doc.split() if word in words]

    # adding the vector representations of the words
    for word in words_in_vocab:
        feature_vector += np.array(word_vector_dict[word])

    # Dividing by the number of words to get the average vector
    if len(words_in_vocab) != 0:
        feature_vector /= len(words_in_vocab)

    return feature_vector

# creating a dataframe of the vectorized documents, seggragated for training validation and test documents
start = time.time()
X_train_wOfv = pd.DataFrame(X_train['News'].apply(average_vectorizer_Word2Vec).tolist(), columns=['Feature'+str(i) for i in range(vec_size)])
X_val_wOfv = pd.DataFrame(X_val['News'].apply(average_vectorizer_Word2Vec).tolist(), columns=['Feature'+str(i) for i in range(vec_size)])
X_test_wOfv = pd.DataFrame(X_test['News'].apply(average_vectorizer_Word2Vec).tolist(), columns=['Feature'+str(i) for i in range(vec_size)])
end = time.time()
print('Time consumed', end-start)

print(f'Training set shape: {X_train_wOfv.shape}')
print(f'Validation set shape: {X_val_wOfv.shape}')
print(f'Test set shape: {X_test_wOfv.shape}')

df_Word2Vec = pd.DataFrame(data['News'].apply(average_vectorizer_Word2Vec).tolist(), columns=['Feature '+str(i) for i in range(vec_size)])
df_Word2Vec

"""### **GloVe**"""

# load the Stanford GloVe model
filename = 'glove.6B.100d.txt.word2vec'
glove_model = KeyedVectors.load_word2vec_format(filename, binary=False)

"""The size of the vector loaded is 100. Hence defining the size to be 100 here"""

glove_vec_size = 100

# Checking the size of the vocabulary
print("Length of the vocabulary is", len(glove_model.index_to_key))

"""I had to delete few words in the file manually. Hence you see 3 words lesser, than the normal file size"""

# Checking the word embedding of a random word
word = "trade"
glove_model[word]

# Checking the word embedding of a random word
word = "price"
glove_model[word]

similar = glove_model.most_similar("price", topn=5)
print(similar)

similar = glove_model.most_similar("trade", topn=5)
print(similar)

glove_model["trade"]

# Retrieving the words present in the GloVe model's vocabulary
glove_words = glove_model.index_to_key

# Creating a dictionary of words and their corresponding vectors
glove_word_vector_dict = dict(zip(glove_model.index_to_key,list(glove_model.vectors)))

# Checking the size of the word vectors
sample_word = next(iter(glove_word_vector_dict))  # Get any word from the dictionary
vector_size = len(glove_word_vector_dict[sample_word])
print(f"Size of each word vector: {vector_size}")

def average_vectorizer_GloVe(doc):
    # Initializing a feature vector for the sentence
    feature_vector = np.zeros((glove_vec_size,), dtype="float64")

    # Creating a list of words in the sentence that are present in the model vocabulary
    words_in_vocab = [word for word in doc.split() if word in glove_words]

    # adding the vector representations of the words
    for word in words_in_vocab:
        feature_vector += np.array(glove_word_vector_dict[word])

    # Dividing by the number of words to get the average vector
    if len(words_in_vocab) != 0:
        feature_vector /= len(words_in_vocab)

    return feature_vector

# creating a dataframe of the vectorized documents, seggragated for training validation and test data
start = time.time()
X_train_Glove = pd.DataFrame(X_train['News'].apply(average_vectorizer_GloVe).tolist(), columns=['Feature'+str(i) for i in range(glove_vec_size)])
X_val_Glove = pd.DataFrame(X_val['News'].apply(average_vectorizer_GloVe).tolist(), columns=['Feature'+str(i) for i in range(glove_vec_size)])
X_test_Glove = pd.DataFrame(X_test['News'].apply(average_vectorizer_GloVe).tolist(), columns=['Feature'+str(i) for i in range(glove_vec_size)])
end = time.time()
print('Time consumed', end-start)

# Check the shape of the splits
print(f'Training set shape: {X_train_Glove.shape}')
print(f'Validation set shape: {X_val_Glove.shape}')
print(f'Test set shape: {X_test_Glove.shape}')

"""Lets see how the training set looks like"""

X_train_Glove

"""As expected, in the above you see 100 columns and 99 rows, as defined in the training data set

## **Sentiment Analysis**

Lets use Sentence Transformers as suggested. Lets load the same
"""

#Define the model with SentenceTransformer
model_st = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

"""###Dataset Encoding"""

#Lets get gpu time. Hurray - we've purchased ColabPro, so we do expect GPU to be available
device_torch = torch.device("cuda")



"""We shall encode the dataset using Sentence Transformers we created above."""

start = time.time()
X_train_st = model_st.encode(X_train['News'].values, show_progress_bar=True, device=device_torch)
X_val_st = model_st.encode(X_val['News'].values, show_progress_bar=True, device=device_torch)
X_test_st = model_st.encode(X_test['News'].values, show_progress_bar=True, device=device_torch)
end = time.time()
print('Time taken : ', end-start)

# Check the shape of the splits
print(f'Training set shape: {X_train_st.shape}')
print(f'Validation set shape: {X_val_st.shape}')
print(f'Test set shape: {X_test_st.shape}')

"""The news column now has a reprentation in the form of a 384 dimensional vector

###Model Building
"""

# defining a function to compute different metrics to check performance of a classification model built using sklearn
def model_performance_classification_sklearn(model, predictors, target):
    """
    Function to compute different metrics to check classification model performance

    model: classifier
    predictors: independent variables
    target: dependent variable
    """
    # predicting using the independent variables
    pred = model.predict(predictors)

    acc = accuracy_score(target, pred)  # to compute Accuracy
    recall = recall_score(target, pred, average='weighted')  # to compute Recall
    precision = precision_score(target, pred, average='weighted')  # to compute Precision
    f1 = f1_score(target, pred, average='weighted')  # to compute F1-score

    # creating a dataframe of metrics
    df_perf = pd.DataFrame(
        {
            "Accuracy": acc,
            "Recall": recall,
            "Precision": precision,
            "F1": f1,
        },
        index=[0],
    )

    return df_perf

# creating a function to plot the confusion matrixdef plot_confusion_matrix(actual, predicted, labels):
# creating a function to plot the confusion matrix
def plot_confusion_matrix(actual, predicted, labels):
    # Convert to string to ensure type consistency
    actual = [str(a) for a in actual]
    predicted = [str(p) for p in predicted]

    cm = confusion_matrix(actual, predicted)
    plt.figure(figsize = (5, 4))

    sns.heatmap(cm, annot = True,  fmt = '.0f',cmap='Blues', xticklabels = labels, yticklabels = labels)
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.title('Confusion Matrix')
    plt.show()

"""###Model Evaluation - Rationale
There is a need to build a model that classifies news into Positive, Negative and Neutral sentiments. Considering this, F1 seems to be a better suited parameter

- Its a conscious decision to use Random Forest model, although we will see if time permits, we could use other models as well

###Random Forest with Word2Vec
"""

#Building the model
rf_word2vec_base = RandomForestClassifier(n_estimators=75, max_depth=14, random_state = 42)

# Fitting on train data
rf_word2vec_base.fit(X_train_wOfv, y_train)

print(f'Training set-X shape: {X_train_wOfv.shape}')
print(f'Training set-y shape: {y_train.shape}')

# Predicting on train data
y_pred_train_base = rf_word2vec_base.predict(X_train_wOfv)

# Predicting on validation data
y_pred_val_base = rf_word2vec_base.predict(X_val_wOfv)

# Predicting on test data
y_pred_test_base = rf_word2vec_base.predict(X_test_wOfv)

print(f'Training set shape: {y_pred_train_base.shape}')
print(f'Validation set shape: {y_pred_val_base.shape}')
print(f'Validation set shape: {y_pred_test_base.shape}')

# Example usage
labels = ['Negative', 'Neutral', 'Positive']  # Define the class labels explicitly
#plot_confusion_matrix(actual, predicted, labels)
print(len(y_test), len(y_pred_test_base))
plot_confusion_matrix(y_test, y_pred_test_base, labels)

#Calculating different metrics on training data
word2vec_base_train = model_performance_classification_sklearn(rf_word2vec_base, X_train_wOfv, y_train)
print("Training performance:\n", word2vec_base_train)

#Calculating different metrics on validation data
word2vec_base_val = model_performance_classification_sklearn(rf_word2vec_base, X_val_wOfv,y_val)
print("Validation performance:\n", word2vec_base_val)

#Calculating different metrics on Test data
word2vec_base_test = model_performance_classification_sklearn(rf_word2vec_base, X_test_wOfv,y_test)
print("Testing performance:\n", word2vec_base_test)

"""### Random Forest with GloVe"""

# Building the model
rf_Glove_base = RandomForestClassifier(n_estimators=60, max_depth=12, random_state = 42)

# Fitting on train data
rf_Glove_base.fit(X_train_Glove, y_train)

# Predicting on train data
y_pred_train_base = rf_Glove_base.predict(X_train_Glove)

# Predicting on test data
y_pred_test_base = rf_Glove_base.predict(X_test_Glove)

#plot_confusion_matrix(actual, predicted, labels)
plot_confusion_matrix(y_test, y_pred_test_base, labels)

#Calculating different metrics on training data
Glove_base_train=model_performance_classification_sklearn(rf_Glove_base, X_train_Glove, y_train)
print("Training performance:\n", Glove_base_train)

#Calculating different metrics on Validation data
Glove_base_val=model_performance_classification_sklearn(rf_Glove_base, X_val_Glove,y_val)
print("Testing performance:\n", Glove_base_val)

#Calculating different metrics on Test data
Glove_base_test=model_performance_classification_sklearn(rf_Glove_base, X_test_Glove,y_test)
print("Testing performance:\n", Glove_base_test)

# training performance comparison
models_train_comp_df = pd.concat(
    [word2vec_base_train.T,Glove_base_train.T],
    axis=1,
)
models_train_comp_df.columns = [
    "Word2vec - Base RF Model",
    "GloVe - Base RF Model"]
print("Training performance comparison:")

models_train_comp_df

# training performance comparison
models_test_comp_df = pd.concat(
    [word2vec_base_test.T,Glove_base_test.T],
    axis=1,
)
models_train_comp_df.columns = [
    "Word2vec - Base RF Model",
    "GloVe - Base RF Model"]
print("Test performance comparison:")

models_test_comp_df

"""###Random Forest with Sentence Transformer"""

# Building the model
rf_SentTrans = RandomForestClassifier(n_estimators=60, max_depth=12, random_state = 42)

# Fitting on train data
rf_SentTrans.fit(X_train_st, y_train)

# Predicting on train data
y_pred_train_base = rf_SentTrans.predict(X_train_st)

# Predicting on train data
y_pred_val_base = rf_SentTrans.predict(X_val_st)

# Predicting on test data
y_pred_test_base = rf_SentTrans.predict(X_test_st)

#Calculating different metrics on training data
st_base_train=model_performance_classification_sklearn(rf_SentTrans, X_train_st, y_train)
print("Training performance:\n", st_base_train)

#Calculating different metrics on Validation data
st_base_val=model_performance_classification_sklearn(rf_SentTrans, X_val_st,y_val)
print("Testing performance:\n", st_base_val)

#Calculating different metrics on Validation data
st_base_test=model_performance_classification_sklearn(rf_SentTrans, X_test_st, y_test)
print("Testing performance:\n", st_base_test)

"""## Tuned Model - With Word2Vec & Glove

###Word2Vec Tuned
"""

# Building the Word2Vec model
start = time.time()
rf_word2vec_Tuned = RandomForestClassifier(n_estimators=75, max_depth=14, random_state = 42)
parameters =  {
    'max_depth' : np.arange(3,7),
    'min_samples_split' : np.arange(5, 12, 2),
    'max_features' : ['log2', 'sqrt', 0.2, 0.4]
}

grid_container = GridSearchCV(rf_word2vec_Tuned, parameters, scoring = 'f1_weighted', cv=5, n_jobs=1)
grid_container = grid_container.fit(X_train_wOfv, y_train)

end = time.time()
print('Time taken', end-start)
#Setting the tuned model to the best estimator
rf_word2vec_Tuned = grid_container.best_estimator_

rf_word2vec_Tuned.fit(X_train_wOfv, y_train)

#Calculating different metrics on training data
word2vec_tuned_train = model_performance_classification_sklearn(rf_word2vec_Tuned, X_train_wOfv, y_train)
print("Training performance:\n", word2vec_tuned_train)

word2vec_tuned_val = model_performance_classification_sklearn(rf_word2vec_Tuned, X_val_wOfv,y_val)
print("Validation performance:\n", word2vec_tuned_val)

#Calculating different metrics on Test data
word2vec_tuned_test = model_performance_classification_sklearn(rf_word2vec_Tuned, X_test_wOfv,y_test)
print("Testing performance:\n", word2vec_tuned_test)

"""###Tuned Glove model"""

# Building the Glove model
start = time.time()
rf_Glove_Tuned = RandomForestClassifier(n_estimators=75, max_depth=14, random_state = 42)
parameters =  {
    'max_depth' : np.arange(3,7),
    'min_samples_split' : np.arange(5, 12, 2),
    'max_features' : ['log2', 'sqrt', 0.2, 0.4]
}

grid_container = GridSearchCV(rf_Glove_Tuned, parameters, scoring = 'f1_weighted', cv=5, n_jobs=1)
grid_container = grid_container.fit(X_train_wOfv, y_train)

end = time.time()
print('Time taken', end-start)
#Setting the tuned model to the best estimator
rf_Glove_Tuned = grid_container.best_estimator_

# Fitting on train data
rf_Glove_Tuned.fit(X_train_Glove, y_train)

#Calculating different metrics on training data
Glove_tuned_train = model_performance_classification_sklearn(rf_Glove_Tuned, X_train_Glove, y_train)
print("Training performance:\n", Glove_tuned_train)

Glove_tuned_val = model_performance_classification_sklearn(rf_Glove_Tuned, X_val_Glove,y_val)
print("Validation performance:\n", Glove_tuned_val)

#Calculating different metrics on Test data
Glove_tuned_test = model_performance_classification_sklearn(rf_Glove_Tuned, X_test_Glove,y_test)
print("Testing performance:\n", Glove_tuned_test)

"""###Tuned Sentence Transformer with RF Model"""

# Building the sentence Xformer model
start = time.time()
rf_SentTrans = RandomForestClassifier(n_estimators=60, max_depth=12, random_state = 42)

parameters =  {
    'max_depth' : np.arange(3,7),
    'min_samples_split' : np.arange(5, 12, 2),
    'max_features' : ['log2', 'sqrt', 0.2, 0.4]
}

grid_container = GridSearchCV(rf_SentTrans, parameters, scoring = 'f1_weighted', cv=5, n_jobs=1)

grid_container = grid_container.fit(X_train_wOfv, y_train)
end = time.time()
print('Time taken', end-start)
#Setting the tuned model to the best estimator
rf_SentTrans = grid_container.best_estimator_

# Fitting on train data
rf_SentTrans.fit(X_train_st, y_train)

#Calculating different metrics on training data
st_tuned_train = model_performance_classification_sklearn(rf_SentTrans, X_train_st, y_train)
print("Training performance:\n", st_base_train)

st_tuned_val = model_performance_classification_sklearn(rf_SentTrans, X_val_st,y_val)
print("Validation performance:\n", st_base_val)

#Calculating different metrics on Test data
st_tuned_test = model_performance_classification_sklearn(rf_SentTrans, X_test_st,y_test)
print("Testing performance:\n", st_base_test)

"""###Model Summary and comparisons"""

# training performance comparison
models_train_comp_df = pd.concat(
    [word2vec_base_train.T,
     Glove_base_train.T,
     st_base_train.T,
     word2vec_tuned_train.T,
     Glove_tuned_train.T,
     st_tuned_train.T,],
    axis=1,
)
models_train_comp_df.columns = [
    "Word2vec - Base RF Model",
    "GloVe - Base RF Model",
    "Sent Xformer - Base RF Model",
    "Word2vec - Tuned RF Model",
    "GloVe - Tuned RF Model",
    "Sent Xformer - Tuned ST Model"]
print("Training performance comparison:")

models_train_comp_df

# validation performance comparison
models_val_comp_df = pd.concat(
    [word2vec_base_val.T,
     Glove_base_val.T,
     st_base_val.T,
     word2vec_tuned_val.T,
     Glove_tuned_val.T,
     st_tuned_val.T,],
    axis=1,
)
models_val_comp_df.columns = [
    "Word2vec - Base RF Model",
    "GloVe - Base RF Model",
    "Sent Xformer - Base RF Model",
    "Word2vec - Tuned RF Model",
    "GloVe - Tuned RF Model",
    "Sent Xformer - Tuned ST Model"]
print("Validation performance comparison:")

models_val_comp_df

"""###Inferences on the selected Model and showcase the Model performance with Test Data
 - As we see all the models do overfit
"""

# testing performance comparison
models_test_comp_df = pd.concat(
    [word2vec_base_test.T,
     Glove_base_test.T,
     st_base_test.T,
     word2vec_tuned_test.T,
     Glove_tuned_test.T,
     st_tuned_test.T,],
    axis=1,
)
models_test_comp_df.columns = [
    "Word2vec - Base RF Model",
    "GloVe - Base RF Model",
    "Sent Xformer Model",
    "Word2vec - Tuned RF Model",
    "GloVe - Tuned RF Model",
    "Sent Xformer - Tuned ST Model"]
print("Testing performance comparison:")

models_test_comp_df

"""###Chosen Model

- As we see from the above three model comparisons of base models with Fine tuned models, the Glove model seems to be performing slightly better than the rest.
- The best amongst the average performance across all models. We decide to go with Glove-Tuned RF Model with Test F1 score of .445
- The validation score of this Tuned RF model being slightly better at .514

## **Weekly News Summarization**

**Vishwa Notes**: It is recommended to run this section of the project independently from the previous sections in order to avoid runtime crashes due to RAM overload.

#### Installing and Importing the necessary libraries
"""

!nvcc --version

# Installation for GPU llama-cpp-python
# uncomment and run the following code in case GPU is being used
!CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python -q
#!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python --force-reinstall --no-cache-dir --verbose

#!pip install transformers datasets torch -q
# Function to download the model from the Hugging Face model hub
from huggingface_hub import hf_hub_download

# Importing the Llama class from the llama_cpp module
from llama_cpp import Llama

from tqdm import tqdm # For progress bar related functionalities
tqdm.pandas()

from huggingface_hub import snapshot_download
from huggingface_hub import HfApi, HfFolder

# Replace 'your_huggingface_token' with your actual token
huggingface_token = "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"

# Save the token to the local Hugging Face configuration
HfFolder.save_token(huggingface_token)

# Verify authentication by listing your models (optional)
api = HfApi()
user_info = api.whoami()
print(f"Authenticated as: {user_info['name']}")

# Specify the model name
model_name = "TheBloke/Mistral-7B-Instruct-v0.2-GGUF"
model_base= "mistral-7b-instruct-v0.2.Q6_K.gguf"

# Path to the GGUF model file
local_dir_path = "/content/drive/MyDrive/mistral-7b"
gguf_model_path = f"{local_dir_path}/mistral-7b-instruct-v0.2.Q6_K.gguf"

# Load the GGUF model using Llama
llm_model = Llama(model_path=gguf_model_path, n_gpu_layers=100, n_ctx=4500)

print("Model loaded successfully!")

print("Local path of mistral model being - ",local_dir_path)

# Generate text using the model
prompt = "Once upon a time, there was this beautiful girl who was roaming in the forest."

response = llm_model(prompt)
print(response['choices'][0]['text'])

"""A quick validation of the llama model is complete

## Model Loading for Summarization - Hugging Face

##### Utility Functions - Public available code picked up -Vishwa
"""

# defining a function to parse the JSON output from the model
def extract_json_data(json_str):
    import json
    try:
        # Find the indices of the opening and closing curly braces
        json_start = json_str.find('{')
        json_end = json_str.rfind('}')

        if json_start != -1 and json_end != -1:
            extracted_category = json_str[json_start:json_end + 1]  # Extract the JSON object
            data_dict = json.loads(extracted_category)
            return data_dict
        else:
            print(f"Warning: JSON object not found in response: {json_str}")
            return {}
    except json.JSONDecodeError as e:
        print(f"Error parsing JSON: {e}")
        return {}

"""####Weekly Data Aggregation- Public available code picked up -Vishwa"""

data["Date"] = pd.to_datetime(data['Date'])  # Convert the 'Date' column to datetime format.
# Group the data by week using the 'Date' column.
weekly_grouped = data.groupby(pd.Grouper(key='Date', freq='W'))
weekly_grouped = weekly_grouped.agg(
    {
        'News': lambda x: ' || '.join(x)  # Join the news values with ' || ' separator.
    }
).reset_index()

print(weekly_grouped.shape)

weekly_grouped.head(10)

#Replicate the weekly date
data_grouped_week = weekly_grouped.copy()

"""#### Defining the response function"""

#Defining the response function
def response_mistral_1(prompt, news):
    model_output = llm_model(
      f"""
      [INST]
      {prompt}
      News Articles: {news}
      [/INST]
      """,
      max_tokens=500, #Complete the code to set the maximum number of tokens the model should generate for this task.
      temperature=0.7, #Complete the code to set the value for temperature.
      top_p=0.9, #Complete the code to set the value for top_p
      top_k=50, #Complete the code to set the value for top_k
      echo=False,
    )

    final_output = model_output["choices"][0]["text"]

    return final_output

"""####Model Evaluation : Checking the model output on a sample

"""

##################Working with the Model-1############################
prompt = "Please summarize the key points from the following article"
news = """The global economy has been experiencing significant shifts in the past year.
Many countries have adopted stimulus measures to mitigate the effects of the pandemic,
while others are facing challenges related to inflation and unemployment.
Experts predict that the economy may take several years to fully recover.
"""
# Call the response function
output = response_mistral_1(prompt, news)

# Print the generated response
print("Generated Response:")
print(output)

###################Working with the model ##############################

##################Working with the Model-2############################
prompt = """You are an expert in stock market news aggregation.
You shall be given multiple news articles, each separater by '||'.
Read through each of the news article and extract the top 3 positive and negative news, that are going to impact the stock's performance. Consider market trends, companies performance, along with market sentiments about the particular company
Return a JSON format in the following way:
{"Positive factors impacting" :[point-1, point-2, point-3]}, "Negative factors impacting" :[point-1, point-2, point-3]
Return only JSON output. I dont want anything else"
"""
news = data['News'].iloc[23]
start = time.time()
summarynews = response_mistral_1(prompt, news)
end = time.time()
print("time taken", end-start)

# Print the generated response
summarynews

###################Working with the model ##############################

##################Working with the Model - 3############################
prompt = """You are an expert stock market analyst. You are given many news articles separated by '||' symbol. Read through each of the news articles, and extract the top 3 positive and negative news, that potentially would impact the stock market's performance. Corraborate the news with company's Quarterly performance, the sector trends.
Return a JSON format in the following way:
{"Positive factors impacting" :[point-1, point-2, point-3]}, "Negative factors impacting" :[point-1, point-2, point-3]
Return only JSON output. Nothing else"
"""
news = data['News'].iloc[19]
start = time.time()
summarynews = response_mistral_1(prompt, news)
end = time.time()
print("time taken", end-start)

# Print the generated response
summarynews

###################Working with the model ##############################

"""Now let us check the model's performance on the weekly data that we had grouped.
Lets use weekly_grouped data to extract news of the 13th week.
"""

news = weekly_grouped['News'].iloc[13]
start = time.time()
summarynews = response_mistral_1(prompt, news)
end = time.time()
print("time taken", end-start)

# Print the generated response
summarynews

"""####Weekly Data Structure

Lets check on the entire weekly data structure that contains data from 18 weeks, from the given stock_news data to the project
"""

start = time.time()
weekly_grouped['Key Events'] = weekly_grouped['News'].progress_apply(lambda x: response_mistral_1(prompt, x))
end = time.time()
print("Time taken", end-start)

weekly_grouped['Key Events'].head(8)

"""While the model seems to have given the text I need, it needs better structural formatting"""

weekly_grouped['formatted_response'] = weekly_grouped['Key Events'].apply(extract_json_data)
weekly_grouped.head()

model_response_parsed = pd.json_normalize(weekly_grouped['formatted_response'])
model_response_parsed.head()

Summary_output = pd.concat([weekly_grouped.reset_index(drop=True), model_response_parsed], axis=1)
Summary_output.drop(['Key Events', 'formatted_response'], axis=1, inplace=True)
Summary_output.columns = ['Week End date', 'News', 'Week Positive events', 'Week Negative events']
Summary_output.head(10)

"""## **Conclusions**

- Given the data set for this project, the daily stock movement is rangebound between 40-60 and around 75 - 120. The movements have been consistent across all the months from Jan till April
 - The distributions are similar and are in coherent open and close avg price - exhibiting a good amount of correlation
 - The stock price that is around 40.24 to start with, eventually ended up at around 48.7 at the end of April. A steady increase, while you look at the averages

- Prediction of the sentiment of the market news was done via different ML models.
 - We encoded them, as well, while the Random Forest Model was used across encodings done.
 - The performance of the model is below par as compared to the toss of a coin. Implying our prediction is below 50% accuracy. We have F1 score, that we consciouly chose to be the metrics of evaluation criteria.
 - I could continue to validate this with Gradient Boost Model as well, but I do not think the results would differ largely
 - Also the data points were low and were not large enough for the Model to perform better
 - Considering the fact that 49% of the sentiments were neutral, it is expected that the ML model would not perform any better. We only had about 28% negative and 23% positive sentiments across the dataset given.

##Summary and Recommendations

- We predicted the sentiments of the market news by using various methods and using Random forest Model
 - The Word2Vec, Glove and Sentence Transformers, were run through the ML model and they yielded results.
 - Amongst these, the **Glove-Tuned RF model** yielded better results than the rest of the other models. We finetuned the model with some parameters. The fine tuning with other models, did not help much to increase any of the four parameters: Accuracy, Recall, Precision or F1.
 - The 'Accuracy' score of all the models was slighly higher at .4865 as compared to the F1 score of .44.

- It is recommended to run this project with a larger data set. The data set given is too miniscule to create a robust model
- I also suggest to get a varied data set, where there are more positive and negative sentiments as against 49% neutral sentiments that were present with this data set shared.

## Summary and Recommendations.. Continued

- The weekly news was very well summarized by the LLM - Mistral 7B
- The seggregation of the top 3 weekly news was performed well by Mistral -7B, along with separating the Positive and negative news.
- Since the daily prices and the closing chart were steady during these three months, we can create a Lagging Sentiment and a leading sentiment and do further exploration. But then having larger data set is mandatory for these
- Integration of this model with a Real-time system, would eventually help the market Business analyst to make informed decision on the purchase or sale of various equities, Mutual Funds or market securities
"""